/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import Ventanas.*;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VEmpleado extends javax.swing.JFrame {
    VPrincipal vPrincipal;
    VCliente VCliente=new VCliente(this);
    VServicioListado VservicioListado = new VServicioListado(this);
    /**
     * Creates new form VEmpleado
     */
    public VEmpleado(VPrincipal vP) {
        initComponents();
        vPrincipal=vP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTipo = new javax.swing.JLabel();
        BtnCerrarSesion = new javax.swing.JToggleButton();
        PanelClientes = new javax.swing.JPanel();
        LblClienteIcono = new javax.swing.JLabel();
        BtnClientes = new javax.swing.JToggleButton();
        PanelFac = new javax.swing.JPanel();
        LblFacIcono = new javax.swing.JLabel();
        BtnFacturacion = new javax.swing.JToggleButton();
        PanelServ = new javax.swing.JPanel();
        LblClienteIcono1 = new javax.swing.JLabel();
        BtnServicios = new javax.swing.JToggleButton();
        PanelCitas = new javax.swing.JPanel();
        LblClienteIcono2 = new javax.swing.JLabel();
        BtnCitas = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Atencion al cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        LblTipo.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N

        BtnCerrarSesion.setText("Cerrar Sesión");
        BtnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        PanelClientes.setPreferredSize(new java.awt.Dimension(260, 130));

        LblClienteIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblClienteIcono.setLabelFor(BtnClientes);
        LblClienteIcono.setText("IMAGEN");

        BtnClientes.setText("Clientes");
        BtnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(BtnClientes))
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(LblClienteIcono)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblClienteIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnClientes)
                .addGap(23, 23, 23))
        );

        PanelFac.setPreferredSize(new java.awt.Dimension(260, 130));

        LblFacIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFacIcono.setLabelFor(BtnFacturacion);
        LblFacIcono.setText("IMAGEN");

        BtnFacturacion.setText("Facturación");

        javax.swing.GroupLayout PanelFacLayout = new javax.swing.GroupLayout(PanelFac);
        PanelFac.setLayout(PanelFacLayout);
        PanelFacLayout.setHorizontalGroup(
            PanelFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFacLayout.createSequentialGroup()
                .addGroup(PanelFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFacLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(BtnFacturacion))
                    .addGroup(PanelFacLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(LblFacIcono)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFacLayout.setVerticalGroup(
            PanelFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFacLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LblFacIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnFacturacion)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelServ.setPreferredSize(new java.awt.Dimension(260, 130));

        LblClienteIcono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblClienteIcono1.setLabelFor(BtnClientes);
        LblClienteIcono1.setText("IMAGEN");

        BtnServicios.setText("Servicios");
        BtnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnServiciosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelServLayout = new javax.swing.GroupLayout(PanelServ);
        PanelServ.setLayout(PanelServLayout);
        PanelServLayout.setHorizontalGroup(
            PanelServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServLayout.createSequentialGroup()
                .addGroup(PanelServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelServLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(LblClienteIcono1))
                    .addGroup(PanelServLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BtnServicios)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        PanelServLayout.setVerticalGroup(
            PanelServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblClienteIcono1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnServicios)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        PanelCitas.setPreferredSize(new java.awt.Dimension(260, 130));

        LblClienteIcono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblClienteIcono2.setLabelFor(BtnClientes);
        LblClienteIcono2.setText("IMAGEN");

        BtnCitas.setText("Citas");

        javax.swing.GroupLayout PanelCitasLayout = new javax.swing.GroupLayout(PanelCitas);
        PanelCitas.setLayout(PanelCitasLayout);
        PanelCitasLayout.setHorizontalGroup(
            PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCitas)
                    .addComponent(LblClienteIcono2))
                .addGap(89, 89, 89))
        );
        PanelCitasLayout.setVerticalGroup(
            PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCitasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblClienteIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCitas)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelServ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PanelClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCitas, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(PanelFac, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 216, Short.MAX_VALUE)
                .addComponent(BtnCerrarSesion)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnCerrarSesion)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        this.setVisible(false);
        vPrincipal.setVisible(true);
        
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int op=JOptionPane.showConfirmDialog(rootPane, "Cerrar el programa?", "Confirmar", JOptionPane.YES_NO_OPTION,2);
       if(op==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Gracias :)");
            this.setVisible(false);
            System.exit(0);  
       }
    }//GEN-LAST:event_formWindowClosing

    private void BtnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientesMouseClicked
        this.setEnabled(false);
        VCliente.setLocationRelativeTo(null);
        VCliente.setVisible(true);
    }//GEN-LAST:event_BtnClientesMouseClicked

    private void BtnServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnServiciosMouseClicked
        this.setEnabled(false);
        VservicioListado.setLocationRelativeTo(null);
        VservicioListado.setVisible(true);
    }//GEN-LAST:event_BtnServiciosMouseClicked

    /**
     * @param args the command line arguments
     */
    //Para establecer el mensaje y esconder o mostrar las opciones disponibles
    public void setTipo(String tipo){
        LblTipo.setText("Usted está registrado como usuario "+tipo);
        if(tipo.equals("General")){
            PanelServ.setVisible(false);
            PanelCitas.setVisible(false);
        }
        else{
             PanelServ.setVisible(true);
            PanelCitas.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnCerrarSesion;
    private javax.swing.JToggleButton BtnCitas;
    private javax.swing.JToggleButton BtnClientes;
    private javax.swing.JToggleButton BtnFacturacion;
    private javax.swing.JToggleButton BtnServicios;
    private javax.swing.JLabel LblClienteIcono;
    private javax.swing.JLabel LblClienteIcono1;
    private javax.swing.JLabel LblClienteIcono2;
    private javax.swing.JLabel LblFacIcono;
    private javax.swing.JLabel LblTipo;
    private javax.swing.JPanel PanelCitas;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JPanel PanelFac;
    private javax.swing.JPanel PanelServ;
    // End of variables declaration//GEN-END:variables
}
