/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;
import Ventanas.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VEmpleado extends javax.swing.JFrame {
    VPrincipal vPrincipal;
    VCliente VCliente=new VCliente(this);
    VServicioListado VservicioListado = new VServicioListado(this);
    VFacturacion VFacturacion = new VFacturacion(this);
    VListarFacturas VListarFacturas = new VListarFacturas(this);
    /**
     * Creates new form VEmpleado
     */
    public VEmpleado(VPrincipal vP) {
        initComponents();
        vPrincipal=vP;
        
        ImageIcon cliIcon = new ImageIcon("src\\imagenes\\client.png");
        Image image = cliIcon.getImage(); // Obtener la imagen
        Image newImage = image.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Redimensionar
        cliIcon = new ImageIcon(newImage);
        LblClienteIcono.setIcon(cliIcon);
        
        ImageIcon factIcon = new ImageIcon("src\\imagenes\\bill.png");
        Image image2 = factIcon.getImage(); // Obtener la imagen
        Image newImage2 = image2.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Redimensionar
        factIcon = new ImageIcon(newImage2);
        LblFacIcono.setIcon(factIcon);
        
        ImageIcon mascIcon = new ImageIcon("src\\imagenes\\pets.png");
        Image image3 = mascIcon.getImage(); // Obtener la imagen
        Image newImage3 = image3.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Redimensionar
        mascIcon = new ImageIcon(newImage3);
        LblMascIcono.setIcon(mascIcon);
        
        ImageIcon servIcon = new ImageIcon("src\\imagenes\\shower.png");
        Image image4 = servIcon.getImage(); // Obtener la imagen
        Image newImage4 = image4.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Redimensionar
        servIcon = new ImageIcon(newImage4);
        LblServIcono.setIcon(servIcon);
        
        ImageIcon citaIcon = new ImageIcon("src\\imagenes\\reserve.png");
        Image image5 = citaIcon.getImage(); // Obtener la imagen
        Image newImage5 = image5.getScaledInstance(50, 50, Image.SCALE_SMOOTH); // Redimensionar
        citaIcon = new ImageIcon(newImage5);
        LblCitaIcono2.setIcon(citaIcon);
        
        ImageIcon vetIcon = new ImageIcon("src\\imagenes\\veterinarian.png");
        Image image6 = vetIcon.getImage(); // Obtener la imagen
        Image newImage6 = image6.getScaledInstance(100, 100, Image.SCALE_SMOOTH); // Redimensionar
        vetIcon = new ImageIcon(newImage6);
        LblVetIcono.setIcon(vetIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTipo = new javax.swing.JLabel();
        BtnCerrarSesion = new javax.swing.JToggleButton();
        PanelClientes = new javax.swing.JPanel();
        LblClienteIcono = new javax.swing.JLabel();
        BtnClientes = new javax.swing.JToggleButton();
        PanelFac = new javax.swing.JPanel();
        LblFacIcono = new javax.swing.JLabel();
        BtnFacturacion = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        PanelServ = new javax.swing.JPanel();
        LblServIcono = new javax.swing.JLabel();
        BtnServicios = new javax.swing.JToggleButton();
        PanelCitas = new javax.swing.JPanel();
        LblCitaIcono2 = new javax.swing.JLabel();
        BtnCitas = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btnMascotas = new javax.swing.JButton();
        LblMascIcono = new javax.swing.JLabel();
        LblVetIcono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Atencion al cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        LblTipo.setFont(new java.awt.Font("Microsoft YaHei", 0, 10)); // NOI18N

        BtnCerrarSesion.setText("Cerrar Sesión");
        BtnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        PanelClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelClientes.setPreferredSize(new java.awt.Dimension(260, 130));

        LblClienteIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblClienteIcono.setLabelFor(BtnClientes);

        BtnClientes.setText("Clientes");
        BtnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnClientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(BtnClientes))
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(LblClienteIcono)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblClienteIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnClientes)
                .addGap(23, 23, 23))
        );

        PanelFac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelFac.setPreferredSize(new java.awt.Dimension(260, 130));

        LblFacIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFacIcono.setLabelFor(BtnFacturacion);

        BtnFacturacion.setText("Facturación");
        BtnFacturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnFacturacionMouseClicked(evt);
            }
        });

        jButton1.setText("Buscar Fact.");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelFacLayout = new javax.swing.GroupLayout(PanelFac);
        PanelFac.setLayout(PanelFacLayout);
        PanelFacLayout.setHorizontalGroup(
            PanelFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFacLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(LblFacIcono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelFacLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BtnFacturacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        PanelFacLayout.setVerticalGroup(
            PanelFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFacLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LblFacIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFacturacion)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PanelServ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelServ.setPreferredSize(new java.awt.Dimension(260, 130));

        LblServIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblServIcono.setLabelFor(BtnClientes);

        BtnServicios.setText("Servicios");
        BtnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnServiciosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelServLayout = new javax.swing.GroupLayout(PanelServ);
        PanelServ.setLayout(PanelServLayout);
        PanelServLayout.setHorizontalGroup(
            PanelServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServLayout.createSequentialGroup()
                .addGroup(PanelServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelServLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(LblServIcono))
                    .addGroup(PanelServLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BtnServicios)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelServLayout.setVerticalGroup(
            PanelServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelServLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblServIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnServicios)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PanelCitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelCitas.setPreferredSize(new java.awt.Dimension(260, 130));

        LblCitaIcono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCitaIcono2.setLabelFor(BtnClientes);

        BtnCitas.setText("Citas");

        javax.swing.GroupLayout PanelCitasLayout = new javax.swing.GroupLayout(PanelCitas);
        PanelCitas.setLayout(PanelCitasLayout);
        PanelCitasLayout.setHorizontalGroup(
            PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCitasLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCitas)
                    .addComponent(LblCitaIcono2))
                .addGap(89, 89, 89))
        );
        PanelCitasLayout.setVerticalGroup(
            PanelCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCitasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblCitaIcono2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCitas)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnMascotas.setText("Mascotas");

        LblMascIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMascIcono.setLabelFor(BtnFacturacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMascotas)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LblMascIcono)
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblMascIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMascotas)
                .addGap(20, 20, 20))
        );

        LblVetIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblVetIcono.setLabelFor(BtnFacturacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnCerrarSesion)
                .addGap(325, 325, 325))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(PanelServ, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PanelFac, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(LblVetIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 66, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelFac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblVetIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        this.setVisible(false);
        vPrincipal.setVisible(true);
        
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int op=JOptionPane.showConfirmDialog(rootPane, "Cerrar el programa?", "Confirmar", JOptionPane.YES_NO_OPTION,2);
       if(op==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Gracias :)");
            this.setVisible(false);
            System.exit(0);  
       }
    }//GEN-LAST:event_formWindowClosing

    private void BtnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnClientesMouseClicked
        this.setEnabled(false);
        VCliente.setLocationRelativeTo(null);
        VCliente.setVisible(true);
    }//GEN-LAST:event_BtnClientesMouseClicked

    private void BtnServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnServiciosMouseClicked
        this.setEnabled(false);
        VservicioListado.setLocationRelativeTo(null);
        VservicioListado.setVisible(true);
    }//GEN-LAST:event_BtnServiciosMouseClicked

    private void BtnFacturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFacturacionMouseClicked
        this.setEnabled(false);
        VFacturacion.setLocationRelativeTo(null);
        VFacturacion.setVisible(true);
    }//GEN-LAST:event_BtnFacturacionMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setEnabled(false);
        //VListarFacturas.setLocationRelativeTo(null);
        VListarFacturas.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    //Para establecer el mensaje y esconder o mostrar las opciones disponibles
    public void setTipo(String tipo){
        LblTipo.setText("Usted está registrado como usuario "+tipo);
        if(tipo.equals("General")){
            PanelServ.setVisible(false);
            PanelCitas.setVisible(false);
        }
        else{
             PanelServ.setVisible(true);
            PanelCitas.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnCerrarSesion;
    private javax.swing.JToggleButton BtnCitas;
    private javax.swing.JToggleButton BtnClientes;
    private javax.swing.JToggleButton BtnFacturacion;
    private javax.swing.JToggleButton BtnServicios;
    private javax.swing.JLabel LblCitaIcono2;
    private javax.swing.JLabel LblClienteIcono;
    private javax.swing.JLabel LblFacIcono;
    private javax.swing.JLabel LblMascIcono;
    private javax.swing.JLabel LblServIcono;
    private javax.swing.JLabel LblTipo;
    private javax.swing.JLabel LblVetIcono;
    private javax.swing.JPanel PanelCitas;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JPanel PanelFac;
    private javax.swing.JPanel PanelServ;
    private javax.swing.JButton btnMascotas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
