/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Controlador.CEmpleados;
import Controlador.CPersonas;
import Controlador.CUsuarios;
import DAO.PersonasDAO;
import DAO.UsuariosDAO;
import Modelo.MPersonas;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author karen
 */
public class VRegistro extends javax.swing.JFrame {

    private PersonasDAO pDAO = new PersonasDAO();
    private CEmpleados cemp = new CEmpleados(pDAO);
    private UsuariosDAO uDAO = new UsuariosDAO();
    private CUsuarios cus = new CUsuarios(uDAO);
    private String tipoRegistro = " "; //E para registrar empleado, C para registrar cliente
    private CPersonas cPersona;
    /**
     * Creates new form VRegistro
     */
    VCliente vCliente;
    VListarEmpleados vEmpleado;

    public VRegistro(VCliente v, CPersonas cPersona) {
        initComponents();
        this.vCliente = v;
        this.cPersona = cPersona;
        tipoRegistro = "C";

        if (tipoRegistro == "C") {
            panelDetalleEmp.setVisible(false);
            PanelCuenta.setVisible(false);
        }

        agregarIcono();
    }

    public VRegistro(VListarEmpleados v) {
        initComponents();
        this.vEmpleado = v;
        tipoRegistro = "E";

        agregarIcono();
    }

    private void agregarIcono() {
        ImageIcon icono = new ImageIcon("src\\imagenes\\add.png");
        setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoEmpleado = new javax.swing.ButtonGroup();
        permisoAdmin = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        panelRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxC = new javax.swing.JTextField();
        TxN = new javax.swing.JTextField();
        TxA = new javax.swing.JTextField();
        TxD = new javax.swing.JTextField();
        TxT = new javax.swing.JTextField();
        TxE = new javax.swing.JTextField();
        panelDetalleEmp = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rdAtenciónCliente = new javax.swing.JRadioButton();
        rdVeterinario = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rdPermisoSi = new javax.swing.JRadioButton();
        rdPermisoNo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        PanelCuenta = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TxtUsuario2 = new javax.swing.JTextField();
        TxtContrasenia2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Registro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelPrincipal.setMinimumSize(new java.awt.Dimension(455, 100));

        panelRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel1.setText("Cédula:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Telefono:");

        jLabel6.setText("Email:");

        javax.swing.GroupLayout panelRegistroLayout = new javax.swing.GroupLayout(panelRegistro);
        panelRegistro.setLayout(panelRegistroLayout);
        panelRegistroLayout.setHorizontalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRegistroLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6))
                        .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxC)
                    .addComponent(TxN)
                    .addComponent(TxA)
                    .addComponent(TxD)
                    .addComponent(TxT)
                    .addComponent(TxE))
                .addContainerGap())
        );
        panelRegistroLayout.setVerticalGroup(
            panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDetalleEmp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jLabel7.setText("Tipo de empleado: ");

        tipoEmpleado.add(rdAtenciónCliente);
        rdAtenciónCliente.setSelected(true);
        rdAtenciónCliente.setText("Atención al Cliente");
        rdAtenciónCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdAtenciónClienteMouseClicked(evt);
            }
        });

        tipoEmpleado.add(rdVeterinario);
        rdVeterinario.setText("Veterinario");
        rdVeterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdVeterinarioMouseClicked(evt);
            }
        });

        jLabel8.setText("¿Tiene permisos de Administrador?");

        permisoAdmin.add(rdPermisoSi);
        rdPermisoSi.setSelected(true);
        rdPermisoSi.setText("Si");

        permisoAdmin.add(rdPermisoNo);
        rdPermisoNo.setText("No");

        javax.swing.GroupLayout panelDetalleEmpLayout = new javax.swing.GroupLayout(panelDetalleEmp);
        panelDetalleEmp.setLayout(panelDetalleEmpLayout);
        panelDetalleEmpLayout.setHorizontalGroup(
            panelDetalleEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(rdVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdAtenciónCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(panelDetalleEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(rdPermisoSi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdPermisoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        panelDetalleEmpLayout.setVerticalGroup(
            panelDetalleEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleEmpLayout.createSequentialGroup()
                .addGroup(panelDetalleEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetalleEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdAtenciónCliente)
                    .addComponent(rdPermisoSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetalleEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdVeterinario)
                    .addComponent(rdPermisoNo)))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetalleEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetalleEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        PanelCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        jLabel13.setText("Usuario:");

        jLabel14.setText("Contraseña:");

        javax.swing.GroupLayout PanelCuentaLayout = new javax.swing.GroupLayout(PanelCuenta);
        PanelCuenta.setLayout(PanelCuentaLayout);
        PanelCuentaLayout.setHorizontalGroup(
            PanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TxtUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtContrasenia2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCuentaLayout.setVerticalGroup(
            PanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtContrasenia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar))
                    .addComponent(PanelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        salir();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        salir();
    }//GEN-LAST:event_formWindowClosing

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        if(tipoRegistro.equals("E")){
            if (!"".equals(TxC.getText()) && !"".equals(TxN.getText()) && !"".equals(TxA.getText()) && !"".equals(TxD.getText()) && !"".equals(TxT.getText()) && !"".equals(TxE.getText())) {
                String cedula = TxC.getText();
                String nombre = TxN.getText();
                String apellido = TxA.getText();
                String dir = TxD.getText();
                String tel = TxT.getText();
                String email = TxE.getText();
                String usuario;
                String contr;
                char AoV = 'x';
                char tipo = 'x';
                if (rdAtenciónCliente.isSelected()) {
                    if (rdPermisoSi.isSelected()) {
                        tipo = 'A';
                    } else {
                        tipo = 'G';
                    }
                    AoV = 'A';
                } else {
                    AoV = 'V';
                }
                if (cemp.listarEmpleado(cedula, 'E') == null) {
                    if (rdAtenciónCliente.isSelected()) {
                        if (!"".equals(TxtUsuario2.getText()) && TxtContrasenia2.getText().length() > 5) {
                            cemp.crearEmpleado(cedula, nombre, apellido, dir, tel, email, AoV);
                            usuario = TxtUsuario2.getText();
                            contr = TxtContrasenia2.getText();
                            MPersonas per = cemp.listarEmpleado(cedula, 'E');
                            int id = per.getPer_id();
                            cus.crearUsuario(usuario, contr, tipo, id);
                            JOptionPane.showMessageDialog(this, "Empleado agregado con exito");
                            salir();
                        } else {
                            JOptionPane.showMessageDialog(this, "Datos de entrada invalidos: \nContraseña debe tener al menos 5 caracteres");
                        }
                    } else if (rdVeterinario.isSelected()) {
                        cemp.crearEmpleado(cedula, nombre, apellido, dir, tel, email, AoV);
                        MPersonas per = cemp.listarEmpleado(cedula, 'E');
                        int id = per.getPer_id();
                        JOptionPane.showMessageDialog(this, "Empleado agregado con exito");
                        salir();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Registros duplicados");
                }
            }
        }else if(tipoRegistro.equals("C")){
            if (!"".equals(TxC.getText()) && !"".equals(TxN.getText()) && !"".equals(TxA.getText()) && !"".equals(TxD.getText()) && !"".equals(TxT.getText()) && !"".equals(TxE.getText())){
                MPersonas cliente = new MPersonas(0, TxC.getText(), TxN.getText(), TxA.getText(), TxD.getText(), TxT.getText(), TxC.getText(), 'C', 'A');
                boolean creado = cPersona.crearCliente(cliente);
                if(creado){
                    JOptionPane.showMessageDialog(this, "Registro Creado");
                    salir();
                }else{
                    JOptionPane.showMessageDialog(this, "Registro Duplicado");
                }
                
                
            }
        }
        
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void rdAtenciónClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdAtenciónClienteMouseClicked
        TxtUsuario2.setEnabled(true);
        TxtContrasenia2.setEnabled(true);
        rdPermisoSi.setEnabled(true);
        rdPermisoNo.setEnabled(true);
    }//GEN-LAST:event_rdAtenciónClienteMouseClicked

    private void rdVeterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdVeterinarioMouseClicked
        TxtUsuario2.setEnabled(false);
        TxtContrasenia2.setEnabled(false);
        rdPermisoSi.setEnabled(false);
        rdPermisoNo.setEnabled(false);
    }//GEN-LAST:event_rdVeterinarioMouseClicked

    public void salir() {
        this.setVisible(false);
        if (tipoRegistro == "E") {
            vEmpleado.setEnabled(true);
            vEmpleado.setVisible(true);
        } else if (tipoRegistro == "C") {
            vCliente.setEnabled(true);
            vCliente.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCuenta;
    private javax.swing.JTextField TxA;
    private javax.swing.JTextField TxC;
    private javax.swing.JTextField TxD;
    private javax.swing.JTextField TxE;
    private javax.swing.JTextField TxN;
    private javax.swing.JTextField TxT;
    private javax.swing.JTextField TxtContrasenia2;
    private javax.swing.JTextField TxtUsuario2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelDetalleEmp;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.ButtonGroup permisoAdmin;
    private javax.swing.JRadioButton rdAtenciónCliente;
    private javax.swing.JRadioButton rdPermisoNo;
    private javax.swing.JRadioButton rdPermisoSi;
    private javax.swing.JRadioButton rdVeterinario;
    private javax.swing.ButtonGroup tipoEmpleado;
    // End of variables declaration//GEN-END:variables
}
