/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Controlador.CServicios;
import DAO.ServiciosDAO;
import Modelo.MServicios;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.internal.ResultSetCache;

/**
 *
 * @author USER
 */
public class VServicioListado extends javax.swing.JFrame {
    MServicios servicio=null;
    ServiciosDAO sDAO=new ServiciosDAO();
    CServicios cserv = new CServicios(sDAO);
    VEmpleado v;
    VServicioRegistro servicioRegistro = new VServicioRegistro(this,cserv);

    public VServicioListado(VEmpleado VEmpleado) {
        initComponents();
        this.v = VEmpleado;

        ImageIcon icono = new ImageIcon("src\\imagenes\\shower.png");
        setIconImage(icono.getImage());
    }

    /**
     * Creates new form VEmpleado
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtCodigoServicio = new javax.swing.JTextField();
        TxtNombreServicio = new javax.swing.JTextField();
        BtnBuscarServicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnNuevoServicio = new javax.swing.JButton();
        BtnRegresar = new javax.swing.JButton();
        BtnActualizarServicio = new javax.swing.JButton();
        BtnEliminarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Listado de Servicios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Precio", "IVA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        TxtNombreServicio.setEditable(false);

        BtnBuscarServicio.setText("Buscar");
        BtnBuscarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBuscarServicioMouseClicked(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel2.setText("Nombre:");

        BtnNuevoServicio.setText("Registrar");
        BtnNuevoServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNuevoServicioMouseClicked(evt);
            }
        });

        BtnRegresar.setText("Regresar");
        BtnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegresarMouseClicked(evt);
            }
        });

        BtnActualizarServicio.setText("Mostrar Todos");
        BtnActualizarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarServicioMouseClicked(evt);
            }
        });

        BtnEliminarServicio.setText("Eliminar");
        BtnEliminarServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarServicioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(BtnRegresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtNombreServicio))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtCodigoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnActualizarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnNuevoServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnEliminarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCodigoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(BtnBuscarServicio))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(BtnActualizarServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminarServicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnNuevoServicio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnRegresar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegresarMouseClicked
        salir();
    }//GEN-LAST:event_BtnRegresarMouseClicked

    private void BtnNuevoServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNuevoServicioMouseClicked
        this.setEnabled(false);
        servicioRegistro.setLocationRelativeTo(null);
        servicioRegistro.setVisible(true);
    }//GEN-LAST:event_BtnNuevoServicioMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        salir();
    }//GEN-LAST:event_formWindowClosing

    private void BtnActualizarServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarServicioMouseClicked
        this.limpiarCampos();
        this.actualizar();
    }//GEN-LAST:event_BtnActualizarServicioMouseClicked

    private void BtnBuscarServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBuscarServicioMouseClicked
        servicio=null;
        String cod = TxtCodigoServicio.getText();
        try {
            int numero = Integer.parseInt(cod);
            servicio=cserv.listarServicio(cod, servicio);
            if(servicio==null){
                JOptionPane.showMessageDialog(rootPane,"Codigo no encontrado, ingrese uno valido o registrelo.","Codigo invalido",WARNING_MESSAGE);
                this.actualizar();
            }
            else{
                DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                Object[] fila=new Object[model.getColumnCount()];
                fila[0]=servicio.getServ_codigo();
                fila[1]=servicio.getServ_nombre();
                fila[2]=servicio.getServ_precio();
                String estado;
                if(servicio.getSer_estado()=='A'){
                    estado="Activo";
                }
                else{
                    estado="Inactivo";
                }
                fila[3]=estado;
                model.addRow(fila);
                jTable1.setModel(model);
                TxtNombreServicio.setText(servicio.getServ_nombre());
                
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un codigo valido", "Codigo invalido", WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnBuscarServicioMouseClicked

    private void BtnEliminarServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarServicioMouseClicked
        if(jTable1.getSelectedRow()!=(-1)){
            int i=jTable1.getSelectedRow();
            String cod = jTable1.getValueAt(i, 0).toString();
            int op=JOptionPane.showConfirmDialog(rootPane,("¿Eliminar servicio con código "+cod+"?"),"Confirmar eliminación",YES_NO_OPTION);
            if(op==0){
                cserv.eliminarServicio(cod,servicio, rootPane);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Primero debe seleccionar un servicio", "No se ha seleccionado un servicio", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtnEliminarServicioMouseClicked

    public void actualizar() {
        jTable1.clearSelection();
        jTable1.setModel(cserv.listarServicios());
    }

    private void salir() {
        this.setVisible(false);
        v.setEnabled(true);
        v.setVisible(true);
        limpiarCampos();
    }

    private void limpiarCampos() {
        TxtCodigoServicio.setText("");
        TxtNombreServicio.setText("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarServicio;
    private javax.swing.JButton BtnBuscarServicio;
    private javax.swing.JButton BtnEliminarServicio;
    private javax.swing.JButton BtnNuevoServicio;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JTextField TxtCodigoServicio;
    private javax.swing.JTextField TxtNombreServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
